import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  exams: [
    {
      _id: 1,
      examinationName: "Mid Term Examination",
      examinationType: "Mid",
      academicYear: "2026 - 2027",
      term: "Second",
      class: 1,
      section: "A",
      startDate: "2026-09-15",
      endDate: "2026-09-15",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-09-25",
      maxMarks: 100,
      passingMarks: 40,
      roomNumber: "Hall A",
      description: "Mid term examination for Class 1.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 2,
      examinationName: "Mid Term Examination",
      examinationType: "Monthly Test",
      academicYear: "2026 - 2027",
      term: "First",
      class: 2,
      section: "A",
      startDate: "2026-09-16",
      endDate: "2026-09-16",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-09-26",
      maxMarks: 100,
      passingMarks: 40,
      roomNumber: "Hall B",
      description: "Mid term examination for Class 2.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 3,
      examinationName: "Mid Term Examination",
      examinationType: "Monthly Test",
      academicYear: "2026 - 2027",
      term: "Final",
      class: 3,
      section: "A",
      startDate: "2026-09-17",
      endDate: "2026-09-17",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-09-27",
      maxMarks: 100,
      passingMarks: 40,
      roomNumber: "Room 101",
      description: "Mid term examination for Class 3.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 4,
      examinationName: "Mid Term Examination",
      examinationType: "Mid",
      academicYear: "2026 - 2027",
      term: "Second",
      class: 4,
      section: "A",
      startDate: "2026-09-18",
      endDate: "2026-09-18",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-09-28",
      maxMarks: 100,
      passingMarks: 40,
      roomNumber: "Room 102",
      description: "Mid term examination for Class 4.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 5,
      examinationName: "Mid Term Examination",
      examinationType: "Monthly Test",
      academicYear: "2026 - 2027",
      term: "First",
      class: 5,
      section: "A",
      startDate: "2026-09-19",
      endDate: "2026-09-19",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-09-29",
      maxMarks: 100,
      passingMarks: 40,
      roomNumber: "Room 103",
      description: "Mid term examination for Class 5.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 6,
      examinationName: "Mid Term Examination",
      examinationType: "Mid",
      academicYear: "2026 - 2027",
      term: "First",
      class: 6,
      section: "A",
      startDate: "2026-09-20",
      endDate: "2026-09-20",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-09-30",
      maxMarks: 100,
      passingMarks: 40,

      roomNumber: "Room 104",
      description: "Mid term examination for Class 6.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 7,
      examinationName: "Mid Term Examination",
      examinationType: "Mid",
      academicYear: "2026 - 2027",
      term: "Third",
      class: 7,
      section: "A",
      startDate: "2026-09-21",
      endDate: "2026-09-21",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-10-01",
      maxMarks: 100,
      passingMarks: 40,

      roomNumber: "Room 201",
      description: "Mid term examination for Class 7.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 8,
      examinationName: "Mid Term Examination",
      examinationType: "Mid",
      academicYear: "2026 - 2027",
      term: "First",
      class: 8,
      section: "A",
      startDate: "2026-09-22",
      endDate: "2026-09-22",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-10-02",
      maxMarks: 100,
      passingMarks: 40,
      roomNumber: "Room 202",
      description: "Mid term examination for Class 8.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 9,
      examinationName: "Board Preparation Test",
      examinationType: "Annual",
      academicYear: "2026 - 2027",
      term: "Third",
      class: 9,
      section: "A",
      startDate: "2026-10-05",
      endDate: "2026-10-05",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-10-15",
      maxMarks: 100,
      passingMarks: 40,

      roomNumber: "Hall B",
      description: "Board preparation test for Class 9.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 10,
      examinationName: "Board Preparation Test",
      examinationType: "Annual",
      academicYear: "2026 - 2027",
      term: "First",
      class: 10,
      section: "A",
      startDate: "2026-10-07",
      endDate: "2026-10-07",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-10-17",
      maxMarks: 100,
      passingMarks: 40,

      roomNumber: "Hall C",
      description: "Board preparation test for Class 10.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 11,
      examinationName: "First Year Examination",
      examinationType: "Annual",
      academicYear: "2026 - 2027",
      term: "Second",
      class: 11,
      section: "A",
      startDate: "2026-10-15",
      endDate: "2026-10-15",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-10-25",
      maxMarks: 100,
      passingMarks: 40,

      roomNumber: "Hall D",
      description: "First year examination for Class 11.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },

    {
      _id: 12,
      examinationName: "Second Year Pre-Board",
      examinationType: "Annual",
      academicYear: "2026 - 2027",
      term: "Final",
      class: 12,
      section: "A",
      startDate: "2026-11-01",
      endDate: "2026-11-01",
      startTime: "09:00 AM",
      endTime: "12:00 PM",
      resultDate: "2026-11-10",
      maxMarks: 100,
      passingMarks: 40,

      roomNumber: "Hall C",
      description: "Second year pre-board examination.",
      instructions: "Bring all required examination stationery.",
      syllabus: null,
      status: "upcoming",
    },
  ],

  loading: false,
  error: null,
};
const examSlice = createSlice({
  name: "exam",
  initialState,
  reducers: {
    addExam: (state, action) => {
      state.exams.push(action.payload);
    },

    updateExamStatus: (state, action) => {
      const { id, status } = action.payload;
      const exam = state.exams.find((exam) => exam._id === id);
      if (exam) {
        exam.status = status;
      }
    },

    deleteExam: (state, action) => {
      state.exams = state.exams.filter((exam) => exam._id !== action.payload);
    },
  },
});

export const { addExam, updateExamStatus, deleteExam } = examSlice.actions;

export default examSlice.reducer;
