import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  students: [
    {
      _id: 1,
      studentId: "STD001",
      admissionNo: "2026-001",
      createdAt: "2026-07-01",
      rollNo: "10A-01",
      firstName: "Ali",
      lastName: "Khan",
      fullName: "Ali Khan",
      gender: "Male",
      dateOfBirth: "2010-05-15",
      bloodGroup: "B+",
      religion: "Islam",
      nationality: "Pakistani",
      cnicOrBForm: "12345-1234567-1",
      email: "ali.khan@gmail.com",
      phone: "03001234567",
      address: "University Town",
      city: "Peshawar",
      province: "KPK",
      postalCode: "25000",
      class: 10,
      section: "A",
      house: "Iqbal House",
      session: "2026-2027",
      parentId: 101,
      fatherName: "Ahmad Khan",
      fatherContact: "03111222333",
      fatherOccupation: "Businessman",
      motherName: "Ayesha Khan",
      motherContact: "03221222333",
      motherOccupation: "Teacher",
      guardianName: "Ahmad Khan",
      guardianRelation: "Father",
      guardianPhone: "03111222333",
      emergencyContactName: "Ahmad Khan",
      emergencyContactNumber: "03111222333",
      profileImage: "",
      previousSchool: "The Educators",
      status: "Active",
    },

    {
      _id: 2,
      studentId: "STD002",
      admissionNo: "2026-002",
      createdAt: "2026-07-03",
      rollNo: "10A-02",
      firstName: "Fatima",
      lastName: "Noor",
      fullName: "Fatima Noor",
      gender: "Female",
      dateOfBirth: "2010-08-21",
      bloodGroup: "A+",
      religion: "Islam",
      nationality: "Pakistani",
      cnicOrBForm: "12345-9876543-2",
      email: "fatima.noor@gmail.com",
      phone: "03019876543",
      address: "Hayatabad",
      city: "Peshawar",
      province: "KPK",
      postalCode: "25000",
      class: 10,
      section: "B",
      house: "Jinnah House",
      session: "2026-2027",
      parentId: 102,
      fatherName: "Noor Ahmad",
      fatherContact: "03144556677",
      fatherOccupation: "Engineer",
      motherName: "Shazia Noor",
      motherContact: "03335556677",
      motherOccupation: "Doctor",
      guardianName: "Noor Ahmad",
      guardianRelation: "Father",
      guardianPhone: "03144556677",
      emergencyContactName: "Noor Ahmad",
      emergencyContactNumber: "03144556677",
      profileImage: "",
      previousSchool: "Beaconhouse",
      status: "Active",
    },

    {
      _id: 3,
      studentId: "STD003",
      admissionNo: "2026-003",
      createdAt: "2026-06-05",
      rollNo: "9B-05",
      firstName: "Usman",
      lastName: "Shah",
      fullName: "Usman Shah",
      gender: "Male",
      dateOfBirth: "2011-02-10",
      bloodGroup: "O+",
      religion: "Islam",
      nationality: "Pakistani",
      cnicOrBForm: "17301-1234567-5",
      email: "usman.shah@gmail.com",
      phone: "03025554444",
      address: "Nowshera Cantt",
      city: "Nowshera",
      province: "KPK",
      postalCode: "24100",
      class: 9,
      section: "B",
      house: "Sir Syed House",
      session: "2026-2027",
      parentId: 103,
      fatherName: "Imran Shah",
      fatherContact: "03006667777",
      fatherOccupation: "Army Officer",
      motherName: "Sadia Shah",
      motherContact: "03007778888",
      motherOccupation: "Housewife",
      guardianName: "Imran Shah",
      guardianRelation: "Father",
      guardianPhone: "03006667777",
      emergencyContactName: "Imran Shah",
      emergencyContactNumber: "03006667777",
      profileImage: "",
      previousSchool: "Army Public School",
      status: "Active",
    },

    {
      _id: 4,
      studentId: "STD004",
      admissionNo: "2026-004",
      createdAt: "2026-06-08",
      rollNo: "8A-11",
      firstName: "Ayesha",
      lastName: "Malik",
      fullName: "Ayesha Malik",
      gender: "Female",
      dateOfBirth: "2012-01-19",
      bloodGroup: "AB+",
      religion: "Islam",
      nationality: "Pakistani",
      cnicOrBForm: "35201-4567890-8",
      email: "ayesha.malik@gmail.com",
      phone: "03451234567",
      address: "Johar Town",
      city: "Lahore",
      province: "Punjab",
      postalCode: "54000",
      class: 8,
      section: "A",
      house: "Liaquat House",
      session: "2026-2027",
      parentId: 104,
      fatherName: "Bilal Malik",
      fatherContact: "03451230000",
      fatherOccupation: "Software Engineer",
      motherName: "Sana Malik",
      motherContact: "03452220000",
      motherOccupation: "Lecturer",
      guardianName: "Bilal Malik",
      guardianRelation: "Father",
      guardianPhone: "03451230000",
      emergencyContactName: "Bilal Malik",
      emergencyContactNumber: "03451230000",
      profileImage: "",
      previousSchool: "Lahore Grammar School",
      status: "Active",
    },

    {
      _id: 5,
      studentId: "STD005",
      admissionNo: "2026-005",
      createdAt: "2026-07-10",
      rollNo: "7C-09",
      firstName: "Hamna",
      lastName: "Mehwish",
      fullName: "Hamna Mehwish",
      gender: "Female",
      dateOfBirth: "2013-09-12",
      bloodGroup: "A-",
      religion: "Islam",
      nationality: "Pakistani",
      cnicOrBForm: "61101-7654321-2",
      email: "hamza.iqbal@gmail.com",
      phone: "03331234567",
      address: "Satellite Town",
      city: "Rawalpindi",
      province: "Punjab",
      postalCode: "46000",
      class: 7,
      section: "C",
      house: "Iqbal House",
      session: "2026-2027",
      parentId: 105,
      fatherName: "Rashid Iqbal",
      fatherContact: "03335557777",
      fatherOccupation: "Bank Manager",
      motherName: "Nadia Iqbal",
      motherContact: "03334446666",
      motherOccupation: "Teacher",
      guardianName: "Rashid Iqbal",
      guardianRelation: "Father",
      guardianPhone: "03335557777",
      emergencyContactName: "Rashid Iqbal",
      emergencyContactNumber: "03335557777",
      profileImage: "",
      previousSchool: "Roots International",
      status: "Inactive",
    },
  ],

  loading: false,
  error: null,
};

const studentSlice = createSlice({
  name: "student",
  initialState,
  reducers: {
    addStudent: (state, action) => {
      state.students.push(action.payload);
    },
    deleteStudent: (state, action) => {
      state.students = state.students.filter(
        (student) => student._id !== action.payload._id,
      );
    },
    // Update student profile
    updateStudent: (state, action) => {
      const index = state.students.findIndex(
        (student) => student._id === action.payload._id,
      );

      if (index !== -1) {
        state.students[index] = {
          ...state.students[index],
          ...action.payload,
        };
      }
    },
    // Change student status
    changeStudentStatus: (state, action) => {
      const student = state.students.find(
        (student) => student._id === action.payload._id,
      );

      if (student) {
        student.status = action.payload.status;
      }
    },
  },
});

export const { addStudent, deleteStudent, changeStudentStatus, updateStudent } =
  studentSlice.actions;
export default studentSlice.reducer;
